name: Build AuthService

on:
  push:
    branches:
      - sushil

  pull_request:
    branches:
      - sushil
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Build Project
        run: ./mvnw clean verify